### ISSUE TITLE
Run on Netlify

### ISSUE THREAD

**Issue by mrevellinHH** [therockstorm/privacy-protect#17]
## Summary

Have you ever tried to run it in netlify already ?

**Comment by therockstorm** [comment]
I haven't. It's deployed on Vercel.

**Comment by mrevellinHH** [comment]
![Capture d’écran 2023-06-12 à 14 08 05](https://github.com/therockstorm/privacy-protect/assets/102026496/fab22b1a-d429-44e2-802c-9dd892efdae5)

Alright thanks =)

It should be the same process but I dont understand why it's not working as I defined the build command to :

- npm run build

What is supposed to do the --host flag ? (Link to external domain? Should we append value to it?)

How did you link the server with port to your domain name?

Thanks for your help

**Comment by mrevellinHH** [comment]
Alright used Vercel (lot easier ^^)

Thanks !
