### ISSUE TITLE
Website not working. Does not accept any password as correct.

### ISSUE THREAD

**Issue by pauldcunningham** [therockstorm/privacy-protect#35]
## Summary

Encrypting a secret on the website works as expected. Decrypting does not work with any password.

## Reproduction steps
Go to https://www.privacyprotect.dev/
message: my secret
password: 1234
Click "Conceal and download secret"

Resulting .html cannot be decrypted in Chrome or Firefox

Chrome
```
2023-10-25T00 25 27.secret.html:186 Uncaught TypeError: Cannot read properties of undefined (reading 'passwordHint')
    at init (2023-10-25T00 25 27.secret.html:186:16)
    at onload (2023-10-25T00 25 27.secret.html:266:25)
```
Firefox
```
Uncaught TypeError: config is undefined
    init file:///C:/Users/xxxx/Downloads/2023-10-25T00 25 27.secret.html:186
    onload file:///C:/Users/xxxx/Downloads/2023-10-25T00 25 27.secret.html:1
```

**Comment by therockstorm** [comment]
Thanks! [This](https://github.com/therockstorm/privacy-protect/commit/aa438a31b5d6096767546dc688d724a5b5835686) should fix it.
